/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AidePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  baseUrl: "http://127.0.0.1:1234/v1",
  selectedModel: "",
  systemPrompt: "You are Aide, an expert AI assistant integrated into Obsidian. Answer the user's request directly and completely, using note context only as evidence. Do not add unsolicited tips, suggestions for future note updates, next steps, follow-up offers, or extra sections. Provide recommendations or ask a follow-up question only when the user explicitly requests them or when they are necessary to answer accurately. Use concise Markdown when it improves readability.",
  temperature: 0.7,
  maxTokens: 8192,
  includeActiveNoteByDefault: true,
  maxContextChars: 24e3,
  autoTitleChat: true,
  showReasoning: true,
  saveChatHistory: true
};

// src/settings.ts
var import_obsidian = require("obsidian");

// src/api/lmStudioClient.ts
var LMStudioClient = class _LMStudioClient {
  /**
   * Cleans the base URL by trimming trailing slashes and ensuring standard structure.
   */
  static sanitizeBaseUrl(url) {
    let clean = url.trim();
    while (clean.endsWith("/")) {
      clean = clean.slice(0, -1);
    }
    if (!clean.startsWith("http://") && !clean.startsWith("https://")) {
      clean = "http://" + clean;
    }
    return clean;
  }
  /**
   * Fetches all available models from the local LM Studio instance.
   */
  static async fetchModels(baseUrl) {
    const cleanBase = this.sanitizeBaseUrl(baseUrl);
    const endpoint = `${cleanBase}/models`;
    try {
      const response = await fetch(endpoint, {
        method: "GET",
        headers: {
          Accept: "application/json"
        }
      });
      if (!response.ok) {
        throw new Error(
          `Failed to fetch models: HTTP ${response.status} ${response.statusText}`
        );
      }
      const data = await response.json();
      if (data && Array.isArray(data.data)) {
        return data.data.map((m) => ({
          id: m.id || m.name || "unknown",
          object: m.object,
          owned_by: m.owned_by
        }));
      } else if (Array.isArray(data)) {
        return data.map((m) => ({
          id: typeof m === "string" ? m : m.id || m.name || "unknown",
          object: m.object,
          owned_by: m.owned_by
        }));
      }
      return [];
    } catch (error) {
      console.error("[LMStudioClient] Error fetching models:", error);
      throw error;
    }
  }
  /**
   * Intelligently parses mixed reasoning & answer text into separate parts.
   */
  static splitReasoningAndAnswer(rawText) {
    if (!rawText) return { reasoning: "", answer: "" };
    const text = rawText.trim();
    const tagMatches = [
      /<think>([\s\S]*?)<\/think>/i,
      /<thought>([\s\S]*?)<\/thought>/i,
      /<reasoning>([\s\S]*?)<\/reasoning>/i,
      /<thinking>([\s\S]*?)<\/thinking>/i,
      /<\|(?:start_of_thought|thought)\|>([\s\S]*?)<\|(?:end_of_thought|endofthought)\>/i,
      /\[(?:thought|think|reasoning)\]([\s\S]*?)\[\/(?:thought|think|reasoning)\]/i,
      /```(?:thought|think)([\s\S]*?)```/i,
      /\|thought\|([\s\S]*?)\|\/thought\|/i
    ];
    for (const regex of tagMatches) {
      const match = text.match(regex);
      if (match && match.index !== void 0) {
        const reasoning = match[1].trim();
        const before = text.slice(0, match.index).trim();
        const after = text.slice(match.index + match[0].length).trim();
        const answer = [before, after].filter(Boolean).join("\n\n").trim();
        if (answer) {
          return { reasoning, answer };
        }
      }
    }
    const closingTagRegex = /(?:<\/think>|<\/thought>|<\/reasoning>|<\/thinking>|<\|endofthought\|>|<\|end_of_thought\|>|<\|im_end\|>|\[\/thought\]|\[\/think\]|\[\/reasoning\]|\|\/thought\||\|endofthought\||```\/thought)([\s\S]*)/i;
    const closingMatch = text.match(closingTagRegex);
    if (closingMatch && closingMatch[1] !== void 0 && closingMatch.index !== void 0) {
      const reasoning = text.slice(0, closingMatch.index).trim();
      const answer = closingMatch[1].trim();
      if (answer) {
        return { reasoning, answer };
      }
    }
    const delimiterRegexes = [
      /(?:\n|^)(?:---|\*\*\*)\s*\n+([\s\S]+)$/i,
      /(?:\n|^)(?:#{1,4}\s*)?(?:\*{1,2})?(?:Final Answer|Answer|Response|Conclusion|Solution|Summary|Sentence)(?:\*{1,2})?[:\s\n]+([\s\S]+)$/i,
      /(?:\n|^)(?:#{1,4}\s*)(?:Output|Result|Explanation)(?:\*{1,2})?[:\s\n]+([\s\S]+)$/i
    ];
    for (const regex of delimiterRegexes) {
      const match = text.match(regex);
      if (match && match.index !== void 0 && match[1]?.trim()) {
        const reasoning = text.slice(0, match.index).trim();
        const answer = match[1].trim();
        if (reasoning.length > 10) {
          return { reasoning, answer };
        }
      }
    }
    return { reasoning: "", answer: text };
  }
  /**
   * Extracts an explicitly labelled conclusion when a model stops after its
   * reasoning channel without producing a separate content channel.
   */
  static extractConclusionFromReasoning(reasoning) {
    const conclusionRegex = /(?:^|[.!?]\s+)(?:so|thus|therefore)\s+(?:the\s+)?(?:final\s+)?(?:answer|response|reply)(?:\s+(?:is|should be))?\s*:\s*([^\n.!?]+(?:[.!?](?=\s|$))?)/gi;
    const matches = Array.from(reasoning.matchAll(conclusionRegex));
    return matches.at(-1)?.[1].trim() ?? "";
  }
  /**
   * Streams chat completion from LM Studio.
   * Supports both delta.reasoning_content (OpenAI / DeepSeek / LM Studio native)
   * and in-stream <think>...</think> tags for standard llama / oss reasoning models.
   */
  static async streamChat(params) {
    const cleanBase = this.sanitizeBaseUrl(params.baseUrl);
    const endpoint = `${cleanBase}/chat/completions`;
    const bodyPayload = {
      model: params.model,
      messages: params.messages,
      temperature: params.temperature ?? 0.7,
      stream: true
    };
    if (params.maxTokens && params.maxTokens > 0) {
      bodyPayload.max_tokens = params.maxTokens;
    }
    if (params.model.toLowerCase().includes("gpt-oss")) {
      bodyPayload.stop = ["<|return|>", "<|call|>"];
    }
    if (params.tools && params.tools.length > 0) {
      bodyPayload.tools = params.tools;
      if (params.toolChoice) {
        bodyPayload.tool_choice = params.toolChoice;
      }
    }
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "text/event-stream"
      },
      body: JSON.stringify(bodyPayload),
      signal: params.signal
    });
    if (!response.ok) {
      let errorText = "";
      try {
        errorText = await response.text();
      } catch (_) {
      }
      throw new Error(
        `LM Studio API error (HTTP ${response.status}): ${errorText || response.statusText}`
      );
    }
    if (!response.body) {
      throw new Error(
        "Response body is empty or readable stream is not supported."
      );
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder("utf-8");
    let streamBuffer = "";
    let fullContent = "";
    let fullReasoning = "";
    let finishReason;
    let accumulatedToolCalls = [];
    const START_TAGS = [
      "<think>",
      "<thought>",
      "<reasoning>",
      "<thinking>",
      "<|thought|>",
      "<|start_of_thought|>",
      "[thought]",
      "[think]",
      "[reasoning]",
      "|thought|",
      "```thought",
      "```think"
    ];
    const END_TAGS = [
      "</think>",
      "</thought>",
      "</reasoning>",
      "</thinking>",
      "<|endofthought|>",
      "<|end_of_thought|>",
      "<|im_end|>",
      "<|end|>",
      "<|eot_id|>",
      "[/thought]",
      "[/think]",
      "[/reasoning]",
      "|/thought|",
      "|endofthought|",
      "```/thought",
      "```end_of_thought",
      "\n\nfinal answer:",
      "\n\n**final answer:**",
      "\n\n### final answer",
      "\n\nanswer:",
      "\n\n**answer:**",
      "\n\n### answer"
    ];
    let inThinkBlock = false;
    let pendingContent = "";
    const processContentBuffer = (forceFlush = false) => {
      while (pendingContent.length > 0) {
        const lowerPending = pendingContent.toLowerCase();
        if (!inThinkBlock) {
          let earliestIdx = -1;
          let matchedTagLen = 0;
          for (const tag of START_TAGS) {
            const idx = lowerPending.indexOf(tag);
            if (idx !== -1 && (earliestIdx === -1 || idx < earliestIdx)) {
              earliestIdx = idx;
              matchedTagLen = tag.length;
            }
          }
          if (earliestIdx !== -1) {
            const before = pendingContent.slice(0, earliestIdx);
            if (before) {
              fullContent += before;
              params.onToken(before, "");
            }
            inThinkBlock = true;
            pendingContent = pendingContent.slice(earliestIdx + matchedTagLen);
          } else {
            if (forceFlush) {
              fullContent += pendingContent;
              params.onToken(pendingContent, "");
              pendingContent = "";
              break;
            }
            let longestPrefixLen = 0;
            for (const tag of START_TAGS) {
              for (let len = Math.min(tag.length - 1, pendingContent.length); len >= 1; len--) {
                if (lowerPending.endsWith(tag.slice(0, len))) {
                  if (len > longestPrefixLen) {
                    longestPrefixLen = len;
                  }
                }
              }
            }
            if (longestPrefixLen > 0) {
              const safeText = pendingContent.slice(
                0,
                pendingContent.length - longestPrefixLen
              );
              if (safeText) {
                fullContent += safeText;
                params.onToken(safeText, "");
              }
              pendingContent = pendingContent.slice(
                pendingContent.length - longestPrefixLen
              );
              break;
            } else {
              fullContent += pendingContent;
              params.onToken(pendingContent, "");
              pendingContent = "";
              break;
            }
          }
        } else {
          let earliestIdx = -1;
          let matchedTagLen = 0;
          let isAnswerSeparator = false;
          for (const tag of END_TAGS) {
            const idx = lowerPending.indexOf(tag);
            if (idx !== -1 && (earliestIdx === -1 || idx < earliestIdx)) {
              earliestIdx = idx;
              matchedTagLen = tag.length;
              if (tag.includes("answer")) {
                isAnswerSeparator = true;
              }
            }
          }
          if (earliestIdx !== -1) {
            const before = pendingContent.slice(0, earliestIdx);
            if (before) {
              fullReasoning += before;
              if (params.onReasoningToken) {
                params.onReasoningToken(before);
              }
              params.onToken("", before);
            }
            inThinkBlock = false;
            if (isAnswerSeparator) {
              pendingContent = pendingContent.slice(earliestIdx);
            } else {
              pendingContent = pendingContent.slice(
                earliestIdx + matchedTagLen
              );
            }
          } else {
            if (forceFlush) {
              fullReasoning += pendingContent;
              if (params.onReasoningToken) {
                params.onReasoningToken(pendingContent);
              }
              params.onToken("", pendingContent);
              pendingContent = "";
              break;
            }
            let longestPrefixLen = 0;
            for (const tag of END_TAGS) {
              for (let len = Math.min(tag.length - 1, pendingContent.length); len >= 1; len--) {
                if (lowerPending.endsWith(tag.slice(0, len))) {
                  if (len > longestPrefixLen) {
                    longestPrefixLen = len;
                  }
                }
              }
            }
            if (longestPrefixLen > 0) {
              const safeText = pendingContent.slice(
                0,
                pendingContent.length - longestPrefixLen
              );
              if (safeText) {
                fullReasoning += safeText;
                if (params.onReasoningToken) {
                  params.onReasoningToken(safeText);
                }
                params.onToken("", safeText);
              }
              pendingContent = pendingContent.slice(
                pendingContent.length - longestPrefixLen
              );
              break;
            } else {
              fullReasoning += pendingContent;
              if (params.onReasoningToken) {
                params.onReasoningToken(pendingContent);
              }
              params.onToken("", pendingContent);
              pendingContent = "";
              break;
            }
          }
        }
      }
    };
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        streamBuffer += decoder.decode(value, { stream: true });
        const lines = streamBuffer.split("\n");
        streamBuffer = lines.pop() ?? "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed || trimmed.startsWith(":")) continue;
          if (trimmed === "data: [DONE]") {
            break;
          }
          if (trimmed.startsWith("data:")) {
            const jsonStr = trimmed.slice(5).trim();
            if (!jsonStr) continue;
            try {
              const parsed = JSON.parse(jsonStr);
              const choice = parsed.choices?.[0];
              if (!choice) continue;
              if (typeof choice.finish_reason === "string") {
                finishReason = choice.finish_reason;
              }
              const delta = choice.delta || {};
              const reasoningDelta = delta.reasoning_content ?? delta.reasoning ?? delta.thought ?? delta.thinking ?? choice.message?.reasoning_content ?? choice.message?.reasoning;
              if (reasoningDelta && typeof reasoningDelta === "string") {
                fullReasoning += reasoningDelta;
                if (params.onReasoningToken) {
                  params.onReasoningToken(reasoningDelta);
                }
                params.onToken("", reasoningDelta);
              }
              if (delta.tool_calls) {
                accumulatedToolCalls.push(...delta.tool_calls);
                if (params.onToolCallChunk) {
                  params.onToolCallChunk(delta.tool_calls);
                }
              }
              const rawContent = delta.content ?? choice.message?.content ?? (typeof choice.text === "string" ? choice.text : null);
              if (rawContent && typeof rawContent === "string") {
                pendingContent += rawContent;
                processContentBuffer(false);
              }
            } catch (parseErr) {
            }
          }
        }
      }
      processContentBuffer(true);
      if (!fullContent.trim() && fullReasoning.trim()) {
        const split = _LMStudioClient.splitReasoningAndAnswer(fullReasoning);
        if (split.answer && split.answer !== fullReasoning) {
          fullContent = split.answer;
          fullReasoning = split.reasoning;
        }
        if (!fullContent.trim()) {
          fullContent = _LMStudioClient.extractConclusionFromReasoning(fullReasoning);
        }
      } else if (fullContent.trim() && !fullReasoning.trim()) {
        const split = _LMStudioClient.splitReasoningAndAnswer(fullContent);
        if (split.reasoning && split.answer) {
          fullContent = split.answer;
          fullReasoning = split.reasoning;
        }
      }
    } finally {
      reader.releaseLock();
    }
    return {
      fullContent,
      fullReasoning,
      finishReason,
      toolCalls: accumulatedToolCalls.length > 0 ? accumulatedToolCalls : void 0
    };
  }
};

// src/settings.ts
var AideSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  modelDropdown = null;
  connectionStatusEl = null;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Aide Settings" });
    new import_obsidian.Setting(containerEl).setName("LM Studio Base URL").setDesc(
      "The base URL of your local LM Studio server (usually http://127.0.0.1:1234/v1)."
    ).addText(
      (text) => text.setPlaceholder("http://127.0.0.1:1234/v1").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
        this.plugin.settings.baseUrl = value.trim() || DEFAULT_SETTINGS.baseUrl;
        await this.plugin.saveSettings();
      })
    ).addButton(
      (btn) => btn.setButtonText("Test & Refresh Models").setCta().onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Connecting...");
        await this.refreshModelsList();
        btn.setDisabled(false);
        btn.setButtonText("Test & Refresh Models");
      })
    );
    this.connectionStatusEl = containerEl.createDiv({
      cls: "lm-copilot-settings-status"
    });
    const modelSetting = new import_obsidian.Setting(containerEl).setName("Default Model").setDesc("The active or loaded model to query in LM Studio.").addDropdown((dropdown) => {
      this.modelDropdown = dropdown;
      this.populateModelDropdown(dropdown);
      dropdown.onChange(async (val) => {
        this.plugin.settings.selectedModel = val;
        await this.plugin.saveSettings();
        this.plugin.updateModelInViews(val);
      });
    });
    new import_obsidian.Setting(containerEl).setName("System Prompt").setDesc(
      "The initial system instructions given to the model for every conversation."
    ).addTextArea((text) => {
      text.setPlaceholder("Enter system prompt...").setValue(this.plugin.settings.systemPrompt).onChange(async (val) => {
        this.plugin.settings.systemPrompt = val;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 4;
      text.inputEl.cols = 40;
    });
    new import_obsidian.Setting(containerEl).setName("Show Reasoning & Thinking").setDesc(
      "Display reasoning thought chains in collapsible blocks for reasoning models (DeepSeek R1, GPT-OSS, QwQ, etc.)."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showReasoning).onChange(async (val) => {
        this.plugin.settings.showReasoning = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include Active Note / Selection by Default").setDesc(
      "Automatically attach currently selected text (or the active note if nothing is selected) as context for new queries. You can always dismiss it with the 'X' button on the context pill in the chat."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeActiveNoteByDefault).onChange(async (val) => {
        this.plugin.settings.includeActiveNoteByDefault = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Context Characters").setDesc(
      "Maximum characters of the active note to send to the model to avoid exceeding context window limits."
    ).addText(
      (text) => text.setPlaceholder("24000").setValue(String(this.plugin.settings.maxContextChars)).onChange(async (val) => {
        const num = parseInt(val, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxContextChars = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Model Parameters" });
    new import_obsidian.Setting(containerEl).setName("Temperature").setDesc(
      "Sampling temperature (0.0 = deterministic and focused, 1.0 = creative)."
    ).addSlider(
      (slider) => slider.setLimits(0, 1.5, 0.05).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (val) => {
        this.plugin.settings.temperature = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max Output Tokens").setDesc(
      "Maximum tokens to generate per response (-1 or 0 for unlimited / model default)."
    ).addText(
      (text) => text.setPlaceholder("4096").setValue(String(this.plugin.settings.maxTokens)).onChange(async (val) => {
        const num = parseInt(val, 10);
        if (!isNaN(num)) {
          this.plugin.settings.maxTokens = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Chat History" });
    new import_obsidian.Setting(containerEl).setName("Save Chat History").setDesc(
      "Automatically persist conversation history across sessions. When disabled, chats exist only in memory during the session."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.saveChatHistory).onChange(async (val) => {
        this.plugin.settings.saveChatHistory = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Clear All Chat History").setDesc(
      `Permanently delete all saved chat sessions (${this.plugin.conversations.length} currently saved).`
    ).addButton(
      (btn) => btn.setButtonText("Clear History").setWarning().onClick(async () => {
        if (confirm(
          "Are you sure you want to delete all chat history? This cannot be undone."
        )) {
          this.plugin.conversations = [];
          await this.plugin.saveConversations();
          const view = this.plugin.getActiveChatView();
          if (view) {
            view.startNewChat();
          }
          new import_obsidian.Notice("Chat history has been cleared.");
          this.display();
        }
      })
    );
  }
  populateModelDropdown(dropdown) {
    dropdown.selectEl.empty();
    if (this.plugin.cachedModels.length === 0) {
      dropdown.addOption("", "No models loaded (click Test & Refresh)");
    } else {
      let found = false;
      for (const model of this.plugin.cachedModels) {
        dropdown.addOption(model.id, model.id);
        if (model.id === this.plugin.settings.selectedModel) {
          found = true;
        }
      }
      if (!found && this.plugin.cachedModels.length > 0) {
        this.plugin.settings.selectedModel = this.plugin.cachedModels[0].id;
        dropdown.setValue(this.plugin.cachedModels[0].id);
      } else {
        dropdown.setValue(this.plugin.settings.selectedModel);
      }
    }
  }
  async refreshModelsList() {
    if (!this.connectionStatusEl) return;
    this.connectionStatusEl.empty();
    try {
      const models = await LMStudioClient.fetchModels(
        this.plugin.settings.baseUrl
      );
      this.plugin.cachedModels = models;
      if (models.length === 0) {
        this.connectionStatusEl.createSpan({
          text: "\u26A0\uFE0F Connected to server, but no models found. Make sure a model is loaded in LM Studio.",
          cls: "lm-copilot-status-warning"
        });
        new import_obsidian.Notice("LM Studio connected, but no models found.");
      } else {
        this.connectionStatusEl.createSpan({
          text: `\u2705 Connected! Found ${models.length} model(s).`,
          cls: "lm-copilot-status-success"
        });
        new import_obsidian.Notice(`Found ${models.length} model(s) from LM Studio!`);
        if (!this.plugin.settings.selectedModel || !models.some((m) => m.id === this.plugin.settings.selectedModel)) {
          this.plugin.settings.selectedModel = models[0].id;
          await this.plugin.saveSettings();
        }
      }
      if (this.modelDropdown) {
        this.populateModelDropdown(this.modelDropdown);
      }
      this.plugin.updateModelInViews(this.plugin.settings.selectedModel);
    } catch (err) {
      this.connectionStatusEl.createSpan({
        text: `\u274C Connection failed: ${err.message || "Make sure LM Studio local server is running."}`,
        cls: "lm-copilot-status-error"
      });
      new import_obsidian.Notice(
        `Failed to connect to LM Studio at ${this.plugin.settings.baseUrl}`
      );
    }
  }
};

// src/views/ChatView.ts
var import_obsidian3 = require("obsidian");

// src/views/HistoryModal.ts
var import_obsidian2 = require("obsidian");
var ChatHistoryModal = class extends import_obsidian2.Modal {
  plugin;
  onSelectChat;
  onNewChat;
  searchQuery = "";
  constructor(app, plugin, onSelectChat, onNewChat) {
    super(app);
    this.plugin = plugin;
    this.onSelectChat = onSelectChat;
    this.onNewChat = onNewChat;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("lm-copilot-history-modal");
    const headerEl = contentEl.createDiv({ cls: "lm-copilot-history-header" });
    headerEl.createEl("h2", { text: "Chat History" });
    const newChatBtn = headerEl.createEl("button", {
      cls: "mod-cta lm-copilot-new-chat-modal-btn",
      text: "+ New Chat"
    });
    newChatBtn.onclick = () => {
      this.close();
      this.onNewChat();
    };
    const searchContainer = contentEl.createDiv({
      cls: "lm-copilot-history-search"
    });
    const searchInput = searchContainer.createEl("input", {
      type: "text",
      placeholder: "Search chats...",
      cls: "lm-copilot-search-input"
    });
    searchInput.oninput = (e) => {
      this.searchQuery = e.target.value.toLowerCase();
      this.renderHistoryList(listContainer);
    };
    const listContainer = contentEl.createDiv({
      cls: "lm-copilot-history-list"
    });
    this.renderHistoryList(listContainer);
    if (this.plugin.conversations.length > 0) {
      const footerEl = contentEl.createDiv({
        cls: "lm-copilot-history-footer"
      });
      const clearBtn = footerEl.createEl("button", {
        cls: "mod-warning lm-copilot-clear-all-btn",
        text: "Clear All History"
      });
      clearBtn.onclick = async () => {
        if (confirm("Are you sure you want to delete all chat history?")) {
          this.plugin.conversations = [];
          await this.plugin.saveConversations();
          this.onNewChat();
          this.close();
        }
      };
    }
  }
  renderHistoryList(containerEl) {
    containerEl.empty();
    const filtered = this.plugin.conversations.filter(
      (c) => (c.title || "Untitled Chat").toLowerCase().includes(this.searchQuery)
    );
    if (filtered.length === 0) {
      const emptyEl = containerEl.createDiv({
        cls: "lm-copilot-history-empty"
      });
      emptyEl.setText(
        this.searchQuery ? "No matching chats found." : "No saved chats yet."
      );
      return;
    }
    filtered.sort((a, b) => b.updatedAt - a.updatedAt);
    for (const chat of filtered) {
      const itemEl = containerEl.createDiv({ cls: "lm-copilot-history-item" });
      const infoEl = itemEl.createDiv({ cls: "lm-copilot-history-info" });
      infoEl.onclick = () => {
        this.onSelectChat(chat);
        this.close();
      };
      const titleEl = infoEl.createDiv({
        cls: "lm-copilot-history-title",
        text: chat.title || "Untitled Chat"
      });
      const metaEl = infoEl.createDiv({ cls: "lm-copilot-history-meta" });
      const dateStr = new Date(chat.updatedAt).toLocaleDateString(void 0, {
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit"
      });
      const msgCount = chat.messages ? chat.messages.length : 0;
      metaEl.createSpan({
        text: `${dateStr} \xB7 ${msgCount} message${msgCount === 1 ? "" : "s"}`
      });
      const latestAssistantModel = [...chat.messages || []].reverse().find((message) => message.role === "assistant" && message.model)?.model;
      if (latestAssistantModel) {
        metaEl.createSpan({
          cls: "lm-copilot-history-model-tag",
          text: latestAssistantModel
        });
      }
      const actionsEl = itemEl.createDiv({ cls: "lm-copilot-history-actions" });
      const editBtn = actionsEl.createEl("button", {
        cls: "clickable-icon lm-copilot-icon-btn",
        attr: { "aria-label": "Rename chat" }
      });
      (0, import_obsidian2.setIcon)(editBtn, "pencil");
      editBtn.onclick = (e) => {
        e.stopPropagation();
        const newTitle = prompt("Rename chat title:", chat.title);
        if (newTitle !== null && newTitle.trim()) {
          chat.title = newTitle.trim();
          chat.updatedAt = Date.now();
          this.plugin.saveConversations();
          this.renderHistoryList(containerEl);
        }
      };
      const deleteBtn = actionsEl.createEl("button", {
        cls: "clickable-icon lm-copilot-icon-btn mod-delete",
        attr: { "aria-label": "Delete chat" }
      });
      (0, import_obsidian2.setIcon)(deleteBtn, "trash-2");
      deleteBtn.onclick = async (e) => {
        e.stopPropagation();
        this.plugin.conversations = this.plugin.conversations.filter(
          (c) => c.id !== chat.id
        );
        await this.plugin.saveConversations();
        this.renderHistoryList(containerEl);
        if (this.plugin.currentConversationId === chat.id) {
          this.onNewChat();
        }
      };
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/ChatView.ts
var AIDE_VIEW_TYPE = "aide-chat-view";
var AideChatView = class extends import_obsidian3.ItemView {
  plugin;
  // UI Elements
  headerEl;
  modelSelectEl;
  contextBarEl;
  messagesContainerEl;
  inputContainerEl;
  inputEl;
  sendBtnEl;
  stopBtnEl;
  statusEl;
  // State
  currentConversation;
  isGenerating = false;
  currentAbortController = null;
  activeContext = null;
  isContextManuallyRemoved = false;
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.currentConversation = this.createNewConversation();
  }
  getViewType() {
    return AIDE_VIEW_TYPE;
  }
  getDisplayText() {
    return "Aide";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("lm-copilot-container");
    this.buildHeader(container);
    this.buildMessagesArea(container);
    this.buildInputArea(container);
    this.updateActiveFileContext();
    this.refreshModelsDropdown();
    this.renderConversation();
    this.focusInput();
  }
  focusInput() {
    if (this.inputEl) {
      setTimeout(() => {
        this.inputEl.focus();
      }, 50);
    }
  }
  async onClose() {
    this.stopGeneration();
  }
  // -------------------------------------------------------------
  // UI Builder Methods
  // -------------------------------------------------------------
  buildHeader(parent) {
    this.headerEl = parent.createDiv({ cls: "lm-copilot-header" });
    const modelGroup = this.headerEl.createDiv({
      cls: "lm-copilot-model-group"
    });
    this.modelSelectEl = modelGroup.createEl("select", {
      cls: "lm-copilot-model-select"
    });
    this.modelSelectEl.onchange = async () => {
      this.plugin.settings.selectedModel = this.modelSelectEl.value;
      await this.plugin.saveSettings();
    };
    const refreshBtn = modelGroup.createEl("button", {
      cls: "clickable-icon lm-copilot-icon-btn",
      attr: { "aria-label": "Refresh Models from LM Studio" }
    });
    (0, import_obsidian3.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.onclick = async () => {
      refreshBtn.addClass("lm-spinning");
      await this.refreshModelsDropdown();
      refreshBtn.removeClass("lm-spinning");
    };
    const headerActions = this.headerEl.createDiv({
      cls: "lm-copilot-header-actions"
    });
    const newChatBtn = headerActions.createEl("button", {
      cls: "clickable-icon lm-copilot-icon-btn",
      attr: { "aria-label": "New Chat" }
    });
    (0, import_obsidian3.setIcon)(newChatBtn, "plus");
    newChatBtn.onclick = () => this.startNewChat();
    const historyBtn = headerActions.createEl("button", {
      cls: "clickable-icon lm-copilot-icon-btn",
      attr: { "aria-label": "Chat History" }
    });
    (0, import_obsidian3.setIcon)(historyBtn, "history");
    historyBtn.onclick = () => {
      new ChatHistoryModal(
        this.app,
        this.plugin,
        (selectedChat) => this.loadConversation(selectedChat),
        () => this.startNewChat()
      ).open();
    };
    const settingsBtn = headerActions.createEl("button", {
      cls: "clickable-icon lm-copilot-icon-btn",
      attr: { "aria-label": "Open Aide Settings" }
    });
    (0, import_obsidian3.setIcon)(settingsBtn, "settings");
    settingsBtn.onclick = () => this.plugin.openSettings();
  }
  buildContextBar(parent) {
    this.contextBarEl = parent.createDiv({ cls: "lm-copilot-context-bar" });
    this.renderContextPill();
  }
  buildMessagesArea(parent) {
    this.messagesContainerEl = parent.createDiv({
      cls: "lm-copilot-messages-container"
    });
  }
  buildInputArea(parent) {
    this.inputContainerEl = parent.createDiv({
      cls: "lm-copilot-input-container"
    });
    this.buildContextBar(this.inputContainerEl);
    this.statusEl = this.inputContainerEl.createDiv({
      cls: "lm-copilot-status-bar"
    });
    const inputWrapper = this.inputContainerEl.createDiv({
      cls: "lm-copilot-input-wrapper"
    });
    this.inputEl = inputWrapper.createEl("textarea", {
      cls: "lm-copilot-textarea",
      attr: {
        placeholder: "Ask Aide... (Shift+Enter for newline)",
        rows: "1"
      }
    });
    this.inputEl.oninput = () => {
      this.inputEl.style.height = "auto";
      this.inputEl.style.height = Math.min(this.inputEl.scrollHeight, 180) + "px";
    };
    this.inputEl.onkeydown = (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.handleSendMessage();
      }
    };
    const buttonsWrapper = inputWrapper.createDiv({
      cls: "lm-copilot-buttons-wrapper"
    });
    this.sendBtnEl = buttonsWrapper.createEl("button", {
      cls: "clickable-icon lm-copilot-send-btn",
      attr: { "aria-label": "Send Message" }
    });
    (0, import_obsidian3.setIcon)(this.sendBtnEl, "send");
    this.sendBtnEl.onclick = () => this.handleSendMessage();
    this.stopBtnEl = buttonsWrapper.createEl("button", {
      cls: "clickable-icon lm-copilot-stop-btn is-hidden",
      attr: { "aria-label": "Stop Generation" }
    });
    (0, import_obsidian3.setIcon)(this.stopBtnEl, "square");
    this.stopBtnEl.onclick = () => this.stopGeneration();
  }
  // -------------------------------------------------------------
  // Context Management
  // -------------------------------------------------------------
  /**
   * Called by main plugin whenever active leaf / file / selection changes.
   */
  async updateActiveFileContext() {
    if (this.isContextManuallyRemoved) return;
    if (!this.plugin.settings.includeActiveNoteByDefault) {
      this.activeContext = null;
      this.renderContextPill();
      return;
    }
    const mdView = this.plugin.getContextMarkdownView();
    const activeFile = mdView?.file || this.app.workspace.getActiveFile();
    if (activeFile && activeFile.extension === "md") {
      try {
        const selection = mdView?.editor?.getSelection()?.trim();
        if (selection && selection.length > 0) {
          let content = selection;
          if (content.length > this.plugin.settings.maxContextChars) {
            content = content.slice(0, this.plugin.settings.maxContextChars) + "\n...[Selection truncated]";
          }
          this.activeContext = {
            type: "selection",
            title: activeFile.basename,
            path: activeFile.path,
            content
          };
        } else {
          let content = await this.app.vault.cachedRead(activeFile);
          if (content.length > this.plugin.settings.maxContextChars) {
            content = content.slice(0, this.plugin.settings.maxContextChars) + "\n...[Context truncated]";
          }
          this.activeContext = {
            type: "active_note",
            title: activeFile.basename,
            path: activeFile.path,
            content
          };
        }
      } catch (err) {
        console.error("Error reading active note / selection context:", err);
        this.activeContext = null;
      }
    } else {
      this.activeContext = null;
    }
    this.renderContextPill();
  }
  renderContextPill() {
    this.contextBarEl.empty();
    if (this.activeContext) {
      const pill = this.contextBarEl.createDiv({
        cls: "lm-copilot-context-pill"
      });
      const isSelection = this.activeContext.type === "selection";
      const iconSpan = pill.createSpan({ cls: "lm-copilot-context-icon" });
      (0, import_obsidian3.setIcon)(iconSpan, isSelection ? "highlighter" : "file-text");
      const titleSpan = pill.createSpan({
        cls: "lm-copilot-context-title",
        text: isSelection ? `${this.activeContext.title}.md (Selection)` : `${this.activeContext.title}.md`
      });
      titleSpan.title = isSelection ? `Selected text (${this.activeContext.content.length} chars) from ${this.activeContext.path}` : `Full note context from ${this.activeContext.path}`;
      const removeBtn = pill.createSpan({
        cls: "lm-copilot-context-remove",
        attr: { "aria-label": "Remove context" }
      });
      (0, import_obsidian3.setIcon)(removeBtn, "x");
      removeBtn.onclick = (e) => {
        e.stopPropagation();
        this.activeContext = null;
        this.isContextManuallyRemoved = true;
        this.renderContextPill();
      };
    } else {
      const mdView = this.plugin.getContextMarkdownView();
      const activeFile = mdView?.file || this.app.workspace.getActiveFile();
      if (activeFile && activeFile.extension === "md") {
        const attachBtn = this.contextBarEl.createDiv({
          cls: "lm-copilot-context-attach-btn"
        });
        const iconSpan = attachBtn.createSpan({
          cls: "lm-copilot-context-icon"
        });
        (0, import_obsidian3.setIcon)(iconSpan, "paperclip");
        attachBtn.createSpan({ text: `Attach ${activeFile.basename}.md` });
        attachBtn.onclick = () => {
          this.isContextManuallyRemoved = false;
          this.updateActiveFileContext();
        };
      }
    }
  }
  // -------------------------------------------------------------
  // Models Management
  // -------------------------------------------------------------
  async refreshModelsDropdown() {
    try {
      const models = await LMStudioClient.fetchModels(
        this.plugin.settings.baseUrl
      );
      this.plugin.cachedModels = models;
      this.updateModelDropdown(this.plugin.settings.selectedModel);
    } catch (err) {
      this.updateModelDropdown(this.plugin.settings.selectedModel);
    }
  }
  updateModelDropdown(selectedModelId) {
    if (!this.modelSelectEl) return;
    this.modelSelectEl.empty();
    const models = this.plugin.cachedModels;
    if (models.length === 0) {
      const opt = this.modelSelectEl.createEl("option", {
        value: "",
        text: "No models found (check LM Studio)"
      });
      opt.disabled = true;
      opt.selected = true;
      return;
    }
    let selectedExists = false;
    for (const m of models) {
      const opt = this.modelSelectEl.createEl("option", {
        value: m.id,
        text: m.id
      });
      if (selectedModelId && m.id === selectedModelId) {
        opt.selected = true;
        selectedExists = true;
      }
    }
    if (!selectedExists && models.length > 0) {
      this.modelSelectEl.value = models[0].id;
      this.plugin.settings.selectedModel = models[0].id;
      this.plugin.saveSettings();
    }
  }
  // -------------------------------------------------------------
  // Conversation Flow & Rendering
  // -------------------------------------------------------------
  createNewConversation() {
    const newConv = {
      id: "conv_" + Date.now() + "_" + Math.random().toString(36).substring(2, 7),
      title: "New Chat",
      createdAt: Date.now(),
      updatedAt: Date.now(),
      messages: []
    };
    this.plugin.currentConversationId = newConv.id;
    return newConv;
  }
  startNewChat() {
    if (this.isGenerating) {
      this.stopGeneration();
    }
    this.isContextManuallyRemoved = false;
    this.currentConversation = this.createNewConversation();
    this.updateActiveFileContext();
    this.renderConversation();
    this.inputEl.value = "";
    this.inputEl.focus();
  }
  loadConversation(conv) {
    if (this.isGenerating) {
      this.stopGeneration();
    }
    this.currentConversation = conv;
    this.plugin.currentConversationId = conv.id;
    const latestAssistantModel = [...conv.messages].reverse().find((message) => message.role === "assistant" && message.model)?.model;
    if (latestAssistantModel && this.plugin.cachedModels.some((m) => m.id === latestAssistantModel)) {
      this.modelSelectEl.value = latestAssistantModel;
      this.plugin.settings.selectedModel = latestAssistantModel;
    }
    this.renderConversation();
  }
  renderConversation() {
    this.messagesContainerEl.empty();
    if (this.currentConversation.messages.length === 0) {
      const emptyStateEl = this.messagesContainerEl.createDiv({
        cls: "lm-copilot-empty-state"
      });
      const iconEl = emptyStateEl.createDiv({ cls: "lm-copilot-empty-icon" });
      (0, import_obsidian3.setIcon)(iconEl, "sparkles");
      emptyStateEl.createEl("h3", { text: "Aide" });
      emptyStateEl.createEl("p", {
        text: "Ask questions, brainstorm ideas, analyze notes, or write content with your local LLMs."
      });
      return;
    }
    for (const msg of this.currentConversation.messages) {
      this.renderMessageElement(msg);
    }
    this.scrollToBottom();
  }
  getOrCreateReasoningElements(msgEl) {
    let container = msgEl.querySelector(
      ".lm-copilot-reasoning-container"
    );
    if (!container) {
      container = msgEl.createDiv({
        cls: "lm-copilot-reasoning-container"
      });
      const headerEl = msgEl.querySelector(".lm-copilot-message-header");
      if (headerEl && headerEl.nextSibling && headerEl.nextSibling !== container) {
        msgEl.insertBefore(container, headerEl.nextSibling);
      }
    }
    if (!this.plugin.settings.showReasoning && !this.isGenerating) {
      container.addClass("is-hidden");
    } else {
      container.removeClass("is-hidden");
    }
    let details = container.querySelector(
      ".lm-copilot-reasoning-details"
    );
    if (!details) {
      details = container.createEl("details", {
        cls: "lm-copilot-reasoning-details"
      });
    }
    let summary = details.querySelector(
      ".lm-copilot-reasoning-summary"
    );
    let summaryTitle;
    if (!summary) {
      summary = details.createEl("summary", {
        cls: "lm-copilot-reasoning-summary"
      });
      const brainIcon = summary.createSpan({
        cls: "lm-copilot-reasoning-icon"
      });
      (0, import_obsidian3.setIcon)(brainIcon, "cpu");
      summaryTitle = summary.createSpan({
        cls: "lm-copilot-reasoning-title",
        text: "Thinking Process"
      });
    } else {
      summaryTitle = summary.querySelector(
        ".lm-copilot-reasoning-title"
      );
    }
    let body = details.querySelector(
      ".lm-copilot-reasoning-body"
    );
    if (!body) {
      body = details.createDiv({
        cls: "lm-copilot-reasoning-body"
      });
    }
    return { container, details, summary, summaryTitle, body };
  }
  renderMessageElement(msg) {
    const msgEl = this.messagesContainerEl.createDiv({
      cls: `lm-copilot-message lm-copilot-message-${msg.role}`
    });
    msgEl.dataset.messageId = msg.id;
    const headerEl = msgEl.createDiv({ cls: "lm-copilot-message-header" });
    const roleName = msg.role === "user" ? "You" : "Aide";
    headerEl.createSpan({ cls: "lm-copilot-message-author", text: roleName });
    if (msg.role === "user" && msg.contextIncluded) {
      const contextBadge = headerEl.createSpan({
        cls: "lm-copilot-message-context-badge"
      });
      const isSelection = msg.contextIncluded.title.includes("(Selection)");
      (0, import_obsidian3.setIcon)(contextBadge, isSelection ? "highlighter" : "file-text");
      contextBadge.createSpan({ text: msg.contextIncluded.title });
      contextBadge.title = `Attached context: ${msg.contextIncluded.path}`;
    }
    if (msg.role === "assistant" && msg.reasoningContent) {
      const reasoningElements = this.getOrCreateReasoningElements(msgEl);
      reasoningElements.body.setText(msg.reasoningContent);
      if (!msg.content) {
        reasoningElements.details.open = true;
      }
    }
    const bodyEl = msgEl.createDiv({
      cls: "lm-copilot-message-body markdown-rendered"
    });
    if (msg.content) {
      import_obsidian3.MarkdownRenderer.render(
        this.app,
        msg.content,
        bodyEl,
        this.activeContext?.path || "",
        this
      );
    } else if (msg.role === "assistant" && msg.reasoningContent) {
      bodyEl.createEl("p", {
        cls: "lm-copilot-reasoning-only-note",
        text: "(Model completed with reasoning output above)"
      });
    }
    const actionsEl = msgEl.createDiv({ cls: "lm-copilot-message-actions" });
    const copyBtn = actionsEl.createEl("button", {
      cls: "clickable-icon lm-copilot-icon-btn",
      attr: { "aria-label": "Copy Markdown" }
    });
    (0, import_obsidian3.setIcon)(copyBtn, "copy");
    copyBtn.onclick = async () => {
      const textToCopy = msg.content || msg.reasoningContent || "";
      await navigator.clipboard.writeText(textToCopy);
      new import_obsidian3.Notice("Copied message to clipboard!");
      (0, import_obsidian3.setIcon)(copyBtn, "check");
      setTimeout(() => (0, import_obsidian3.setIcon)(copyBtn, "copy"), 1500);
    };
    return msgEl;
  }
  scrollToBottom() {
    if (!this.messagesContainerEl) return;
    this.messagesContainerEl.scrollTop = this.messagesContainerEl.scrollHeight;
  }
  scrollExchangeIntoView(userEl) {
    if (!this.messagesContainerEl) return;
    const container = this.messagesContainerEl;
    if (userEl) {
      const userTop = userEl.offsetTop;
      const exchangeHeight = container.scrollHeight - userTop;
      if (exchangeHeight <= container.clientHeight + 60) {
        container.scrollTop = Math.max(0, userTop - 12);
        return;
      }
    }
    container.scrollTop = container.scrollHeight;
  }
  // -------------------------------------------------------------
  // Chat Generation Logic
  // -------------------------------------------------------------
  async handleSendMessage() {
    const text = this.inputEl.value.trim();
    if (!text || this.isGenerating) return;
    const model = this.modelSelectEl.value || this.plugin.settings.selectedModel;
    if (!model) {
      new import_obsidian3.Notice("Please select or load a model in LM Studio first.");
      return;
    }
    if (this.currentConversation.messages.length === 0) {
      this.messagesContainerEl.empty();
    }
    const isSelectionContext = this.activeContext?.type === "selection";
    const userMsg = {
      id: "msg_" + Date.now() + "_u",
      role: "user",
      content: text,
      timestamp: Date.now(),
      contextIncluded: this.activeContext ? {
        title: isSelectionContext ? `${this.activeContext.title} (Selection)` : this.activeContext.title,
        path: this.activeContext.path,
        preview: this.activeContext.content.slice(0, 300)
      } : void 0
    };
    this.currentConversation.messages.push(userMsg);
    const userMsgEl = this.renderMessageElement(userMsg);
    this.scrollExchangeIntoView(userMsgEl);
    if (this.currentConversation.messages.length === 1 && this.currentConversation.title === "New Chat") {
      const generatedTitle = text.slice(0, 32).replace(/[\r\n]+/g, " ");
      this.currentConversation.title = generatedTitle;
    }
    this.inputEl.value = "";
    this.inputEl.style.height = "auto";
    const apiMessages = [];
    if (this.plugin.settings.systemPrompt) {
      apiMessages.push({
        role: "system",
        content: this.plugin.settings.systemPrompt
      });
    }
    for (let i = 0; i < this.currentConversation.messages.length; i++) {
      const m = this.currentConversation.messages[i];
      if (m.role === "user") {
        let messageContent = m.content;
        if (m.contextIncluded && i === this.currentConversation.messages.length - 1 && this.activeContext) {
          const contextHeader = this.activeContext.type === "selection" ? `[Selected text from Note: "${this.activeContext.title}" (${this.activeContext.path})]` : `[Current Note: "${this.activeContext.title}" (${this.activeContext.path})]`;
          messageContent = `${contextHeader}
\`\`\`markdown
${this.activeContext.content}
\`\`\`

User Question:
${m.content}`;
        }
        apiMessages.push({
          role: "user",
          content: messageContent
        });
      } else if (m.role === "assistant") {
        apiMessages.push({
          role: "assistant",
          content: m.content || m.reasoningContent || ""
        });
      }
    }
    this.isGenerating = true;
    this.setGeneratingUI(true);
    this.currentAbortController = new AbortController();
    const assistantMsg = {
      id: "msg_" + Date.now() + "_a",
      role: "assistant",
      content: "",
      model,
      reasoningContent: "",
      timestamp: Date.now()
    };
    this.currentConversation.messages.push(assistantMsg);
    const assistantMsgEl = this.renderMessageElement(assistantMsg);
    const bodyEl = assistantMsgEl.querySelector(
      ".lm-copilot-message-body"
    );
    this.scrollExchangeIntoView(userMsgEl);
    let accumulatedContent = "";
    let accumulatedReasoning = "";
    let lastRenderTime = 0;
    try {
      this.statusEl.setText("Connecting to model...");
      const result = await LMStudioClient.streamChat({
        baseUrl: this.plugin.settings.baseUrl,
        model,
        messages: apiMessages,
        temperature: this.plugin.settings.temperature,
        maxTokens: this.plugin.settings.maxTokens,
        signal: this.currentAbortController.signal,
        onToken: (contentChunk, reasoningChunk) => {
          if (reasoningChunk) {
            accumulatedReasoning += reasoningChunk;
            const elements = this.getOrCreateReasoningElements(assistantMsgEl);
            elements.body.setText(accumulatedReasoning);
            if (!elements.details.open) {
              elements.details.open = true;
            }
            if (!accumulatedContent) {
              this.statusEl.setText("Thinking...");
              elements.summaryTitle.setText("Thinking...");
            }
            if (this.messagesContainerEl.scrollHeight > this.messagesContainerEl.clientHeight + 40) {
              this.scrollToBottom();
            }
          }
          if (contentChunk) {
            accumulatedContent += contentChunk;
            this.statusEl.setText("Generating response...");
            const reasoningElements = assistantMsgEl.querySelector(
              ".lm-copilot-reasoning-container"
            );
            if (reasoningElements) {
              const summaryTitle = reasoningElements.querySelector(
                ".lm-copilot-reasoning-title"
              );
              if (summaryTitle) {
                summaryTitle.setText("Thinking Process");
              }
            }
            const now = Date.now();
            if (now - lastRenderTime > 80) {
              bodyEl.empty();
              import_obsidian3.MarkdownRenderer.render(
                this.app,
                accumulatedContent,
                bodyEl,
                this.activeContext?.path || "",
                this
              );
              lastRenderTime = now;
              if (this.messagesContainerEl.scrollHeight > this.messagesContainerEl.clientHeight + 40) {
                this.scrollToBottom();
              }
            }
          }
        }
      });
      assistantMsg.content = (result.fullContent || accumulatedContent).trim();
      assistantMsg.reasoningContent = (result.fullReasoning || accumulatedReasoning).trim();
      if (assistantMsg.reasoningContent && !assistantMsg.content) {
        const split = LMStudioClient.splitReasoningAndAnswer(
          assistantMsg.reasoningContent
        );
        if (split.answer && split.reasoning) {
          assistantMsg.content = split.answer;
          assistantMsg.reasoningContent = split.reasoning;
        }
      } else if (assistantMsg.content && !assistantMsg.reasoningContent) {
        const split = LMStudioClient.splitReasoningAndAnswer(
          assistantMsg.content
        );
        if (split.reasoning && split.answer) {
          assistantMsg.content = split.answer;
          assistantMsg.reasoningContent = split.reasoning;
        }
      }
      const reasoningEl = assistantMsgEl.querySelector(
        ".lm-copilot-reasoning-container"
      );
      if (assistantMsg.reasoningContent) {
        const elements = this.getOrCreateReasoningElements(assistantMsgEl);
        elements.body.setText(assistantMsg.reasoningContent);
        elements.summaryTitle.setText("Thinking Process");
        elements.details.open = !assistantMsg.content;
        elements.details.ontoggle = () => {
          this.scrollExchangeIntoView(userMsgEl);
        };
        if (!this.plugin.settings.showReasoning) {
          elements.container.addClass("is-hidden");
        } else {
          elements.container.removeClass("is-hidden");
        }
      } else if (reasoningEl) {
        reasoningEl.addClass("is-hidden");
      }
      bodyEl.empty();
      if (!assistantMsg.content && assistantMsg.reasoningContent) {
        const completionNote = result.finishReason === "length" ? "Model reached the output-token limit while reasoning, before it produced a final response. Increase Max Output Tokens and try again." : "Model completed with reasoning output but did not produce a separate final response.";
        bodyEl.createEl("p", {
          cls: "lm-copilot-reasoning-only-note",
          text: completionNote
        });
      } else {
        await import_obsidian3.MarkdownRenderer.render(
          this.app,
          assistantMsg.content,
          bodyEl,
          this.activeContext?.path || "",
          this
        );
      }
    } catch (err) {
      if (err.name === "AbortError" || this.currentAbortController?.signal.aborted) {
        assistantMsg.content = accumulatedContent + "\n\n*[Generation stopped by user]*";
      } else {
        console.error("[Aide] Stream error:", err);
        assistantMsg.content = accumulatedContent + `

> \u26A0\uFE0F **Error:** ${err.message || "Failed to communicate with LM Studio."}`;
      }
      bodyEl.empty();
      await import_obsidian3.MarkdownRenderer.render(
        this.app,
        assistantMsg.content,
        bodyEl,
        this.activeContext?.path || "",
        this
      );
    } finally {
      this.isGenerating = false;
      this.currentAbortController = null;
      this.setGeneratingUI(false);
      this.statusEl.empty();
      this.currentConversation.updatedAt = Date.now();
      await this.saveActiveConversation();
      this.scrollExchangeIntoView(userMsgEl);
    }
  }
  stopGeneration() {
    if (this.currentAbortController) {
      this.currentAbortController.abort();
    }
    this.isGenerating = false;
    this.setGeneratingUI(false);
    this.statusEl.empty();
  }
  setGeneratingUI(isGenerating) {
    if (isGenerating) {
      this.sendBtnEl.addClass("is-hidden");
      this.stopBtnEl.removeClass("is-hidden");
    } else {
      this.sendBtnEl.removeClass("is-hidden");
      this.stopBtnEl.addClass("is-hidden");
    }
  }
  async saveActiveConversation() {
    if (!this.plugin.settings.saveChatHistory) {
      return;
    }
    const idx = this.plugin.conversations.findIndex(
      (c) => c.id === this.currentConversation.id
    );
    if (idx >= 0) {
      this.plugin.conversations[idx] = this.currentConversation;
    } else {
      this.plugin.conversations.push(this.currentConversation);
    }
    await this.plugin.saveConversations();
  }
};

// src/main.ts
var AidePlugin = class extends import_obsidian4.Plugin {
  settings = DEFAULT_SETTINGS;
  conversations = [];
  currentConversationId = "";
  cachedModels = [];
  lastActiveMarkdownView = null;
  get historyFilePath() {
    return `${this.manifest.dir}/history.json`;
  }
  async onload() {
    console.log("[Aide] Loading plugin");
    await this.loadPluginData();
    this.registerView(AIDE_VIEW_TYPE, (leaf) => new AideChatView(leaf, this));
    this.addRibbonIcon("bot", "Open Aide", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open",
      name: "Open",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "new-aide-chat",
      name: "New chat session",
      callback: async () => {
        await this.activateView();
        const view = this.getActiveChatView();
        if (view) {
          view.startNewChat();
        }
      }
    });
    this.addCommand({
      id: "view-aide-chat-history",
      name: "View chat history",
      callback: () => {
        new ChatHistoryModal(
          this.app,
          this,
          (chat) => {
            this.activateView().then(() => {
              const view = this.getActiveChatView();
              if (view) view.loadConversation(chat);
            });
          },
          () => {
            this.activateView().then(() => {
              const view = this.getActiveChatView();
              if (view) view.startNewChat();
            });
          }
        ).open();
      }
    });
    this.addCommand({
      id: "refresh-lm-studio-models",
      name: "Refresh available models from LM Studio",
      callback: async () => {
        try {
          const models = await LMStudioClient.fetchModels(
            this.settings.baseUrl
          );
          this.cachedModels = models;
          new import_obsidian4.Notice(`Found ${models.length} model(s) from LM Studio`);
          this.updateModelInViews(this.settings.selectedModel);
        } catch (err) {
          new import_obsidian4.Notice(`Failed to fetch models: ${err.message}`);
        }
      }
    });
    this.addSettingTab(new AideSettingTab(this.app, this));
    this.lastActiveMarkdownView = this.app.workspace.getActiveViewOfType(
      import_obsidian4.MarkdownView
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf?.view instanceof import_obsidian4.MarkdownView) {
          this.lastActiveMarkdownView = leaf.view;
        }
        this.updateContextInViews();
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", (_, view) => {
        if (view instanceof import_obsidian4.MarkdownView) {
          this.lastActiveMarkdownView = view;
        }
        this.updateContextInViews();
      })
    );
    this.registerDomEvent(document, "selectionchange", () => {
      const activeEl = document.activeElement;
      if (activeEl && activeEl.closest(".lm-copilot-container")) {
        return;
      }
      this.updateContextInViews();
    });
    this.fetchModelsInBackground();
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(AIDE_VIEW_TYPE);
  }
  // -------------------------------------------------------------
  // View Lifecycle & Helpers
  // -------------------------------------------------------------
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(AIDE_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: AIDE_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      const view = this.getActiveChatView();
      if (view) {
        view.focusInput();
      }
    }
  }
  getActiveChatView() {
    const leaves = this.app.workspace.getLeavesOfType(AIDE_VIEW_TYPE);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  getContextMarkdownView() {
    return this.lastActiveMarkdownView;
  }
  openSettings() {
    const settings = this.app.setting;
    settings.open();
    settings.openTabById(this.manifest.id);
  }
  updateContextInViews() {
    const leaves = this.app.workspace.getLeavesOfType(AIDE_VIEW_TYPE);
    for (const leaf of leaves) {
      if (leaf.view instanceof AideChatView) {
        leaf.view.updateActiveFileContext();
      }
    }
  }
  updateModelInViews(modelId) {
    const leaves = this.app.workspace.getLeavesOfType(AIDE_VIEW_TYPE);
    for (const leaf of leaves) {
      if (leaf.view instanceof AideChatView) {
        leaf.view.updateModelDropdown(modelId);
      }
    }
  }
  async fetchModelsInBackground() {
    try {
      const models = await LMStudioClient.fetchModels(this.settings.baseUrl);
      this.cachedModels = models;
      if (!this.settings.selectedModel && models.length > 0) {
        this.settings.selectedModel = models[0].id;
        await this.saveSettings();
      }
      this.updateModelInViews(this.settings.selectedModel);
    } catch (_) {
    }
  }
  // -------------------------------------------------------------
  // Storage / Persistence
  // -------------------------------------------------------------
  async loadPluginData() {
    const data = await this.loadData();
    if (data && data.settings) {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, data.settings);
    } else if (data && !data.settings && typeof data.baseUrl === "string") {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    } else {
      this.settings = Object.assign({}, DEFAULT_SETTINGS);
    }
    await this.loadConversations(data);
  }
  async loadConversations(legacyData) {
    const adapter = this.app.vault.adapter;
    const historyPath = this.historyFilePath;
    try {
      if (await adapter.exists(historyPath)) {
        const raw = await adapter.read(historyPath);
        const parsed = JSON.parse(raw);
        this.conversations = Array.isArray(parsed) ? parsed : [];
        if (this.migrateConversationModels()) {
          await this.saveConversations();
        }
        return;
      }
    } catch (err) {
      console.error("[Aide] Error reading history.json:", err);
    }
    if (legacyData && Array.isArray(legacyData.conversations) && legacyData.conversations.length > 0) {
      console.log(
        `[Aide] Migrating ${legacyData.conversations.length} conversation(s) from data.json to history.json`
      );
      this.conversations = legacyData.conversations;
      this.migrateConversationModels();
      await this.saveConversations();
      await this.saveSettings();
    } else {
      this.conversations = [];
    }
  }
  /** Moves the legacy conversation model onto each historical assistant message. */
  migrateConversationModels() {
    let changed = false;
    for (const conversation of this.conversations) {
      if (conversation.model) {
        for (const message of conversation.messages || []) {
          if (message.role === "assistant" && !message.model) {
            message.model = conversation.model;
            changed = true;
          }
        }
        delete conversation.model;
        changed = true;
      }
    }
    return changed;
  }
  async saveSettings() {
    const data = {
      settings: this.settings
    };
    await this.saveData(data);
  }
  async saveConversations() {
    if (!this.settings.saveChatHistory) {
      return;
    }
    const adapter = this.app.vault.adapter;
    const historyPath = this.historyFilePath;
    try {
      await adapter.write(
        historyPath,
        JSON.stringify(this.conversations, null, 2)
      );
    } catch (err) {
      console.error("[Aide] Error writing history.json:", err);
    }
  }
};
